Create database QLCCHNQ;
use QLCCHNQ;

CREATE TABLE BANGCAP (
   SOHIEUBANG           VARCHAR(5)           NOT NULL,
   SOVAOSO              VARCHAR(20)          NOT NULL,
   MANV                 CHAR(10)             NOT NULL,
   NGAYCAPBANG          DATETIME             NULL,
   XEPLOAI              VARCHAR(100)         NULL,
   HINHTHUCDAOTAO       VARCHAR(100)         NULL,
   NGUOICAP             VARCHAR(100)         NULL,
   CHUYENNGANHDAOTAO    VARCHAR(100)         NULL,
   THOIGIANDAOTAO       DATETIME             NULL,
   THOIGIANKETTHUCDAOTAO DATETIME            NULL,
   NOICAP               VARCHAR(100)         NULL,
   PRIMARY KEY (SOHIEUBANG, SOVAOSO, MANV),
   INDEX SO_HUU_BANG_CAP_FK (MANV)
);

CREATE TABLE BEN_NNQ (
    MANHUONGQUYEN VARCHAR(10) NOT NULL,
    HOTEN VARCHAR(100) NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DIACHI VARCHAR(200) NOT NULL,
    PRIMARY KEY (MANHUONGQUYEN)
);

CREATE TABLE GOINHUONGQUYEN (
    MAGOI VARCHAR(20) NOT NULL,
    TENGOI VARCHAR(255) NOT NULL,
    VONDAUTU DECIMAL(15,4) NOT NULL,
    MOTAGOI TEXT NOT NULL,
    PRIMARY KEY (MAGOI)
);

CREATE TABLE HOPDONG (
    MAHD VARCHAR(20) NOT NULL,
    CHIPHITONG DECIMAL(15,4) NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    MANHUONGQUYEN VARCHAR(10) NOT NULL,
    MAGOI VARCHAR(20) NOT NULL,
    PRIMARY KEY (MAHD, MANHUONGQUYEN)
);

CREATE TABLE BAOCAO (
   MABAOCAO CHAR(10) NOT NULL,
   MaXacThuc char(15) NOT NULL,
   MACH VARCHAR(10) NOT NULL,
   LOAIBAOCAO VARCHAR(100) NULL,
   NGAYBAOCAO DATETIME NULL,
   NOIDUNGBAOCAO TEXT NULL,
   PRIMARY KEY (MABAOCAO),
   DOANHTHU FLOAT,
   INDEX GUI_THONG_TIN_FK (MACH)
);


CREATE TABLE CTPN (
   MAPHIEUNHAP CHAR(10) NOT NULL,
   MAHANG VARCHAR(20) NOT NULL,
   SOLUONGNHAP INT NOT NULL,
   DONGIANHAP DECIMAL(15,2) NOT NULL,
   PRIMARY KEY (MAPHIEUNHAP, MAHANG)
);

CREATE TABLE CTPX (
   MAPHIEUXUAT CHAR(10) NOT NULL,
   MAHANG VARCHAR(20) NOT NULL,
   SOLUONGXUAT INT NOT NULL,
   DONGIAXUAT DECIMAL(15,2) NOT NULL,
   DONVITINH VARCHAR(100) NOT NULL,
   GIAMGIABAN FLOAT NULL,
   PRIMARY KEY (MAPHIEUXUAT, MAHANG)
);

CREATE TABLE CUAHANGNHUONGQUYEN (
   MACH VARCHAR(10) NOT NULL,
   DIACHI VARCHAR(200) NOT NULL,
   NGAYKHAITRUONG DATETIME NOT NULL,
   MASOTHUE VARCHAR(15) NOT NULL,
   MANHUONGQUYEN VARCHAR(10) NOT NULL,
   MAHD VARCHAR(20) NOT NULL,
   PRIMARY KEY (MACH, MANHUONGQUYEN, MAHD),
   UNIQUE KEY UQ_CUAHANGNHUONGQUYEN_MACH (MACH)
);

CREATE TABLE HANG (
   MAHANG VARCHAR(20) NOT NULL,
   MAKHO VARCHAR(20) NOT NULL,
   TENHANG VARCHAR(255) NOT NULL,
   DONVIDOLUONG VARCHAR(50) NOT NULL,
   GIANHAP DECIMAL(15,2) NOT NULL,
   GIABAN DECIMAL(15,2) NOT NULL,
   LOAIHANG VARCHAR(255) NOT NULL,
   PRIMARY KEY (MAHANG)
);

CREATE TABLE KHO (
   MAKHO VARCHAR(20) NOT NULL,
   TENKHO VARCHAR(255) NOT NULL,
   DIACHI VARCHAR(200) NOT NULL,
   PRIMARY KEY (MAKHO)
);

CREATE TABLE NGUOITHAN (
   TENNT VARCHAR(100) NOT NULL,
   QUANHE VARCHAR(200) NOT NULL,
   MANV CHAR(10) NOT NULL,
   SDTNT CHAR(10) NULL,
   PRIMARY KEY (TENNT, QUANHE,MANV),
   INDEX ASSOCIATION_15_FK (MANV)
);

CREATE TABLE NHANVIEN (
   MANV CHAR(10) NOT NULL,
   MAQL CHAR(10) NULL,
   MAPB CHAR(5) NOT NULL,
   HOTEN VARCHAR(100) NOT NULL,
   EMAIL VARCHAR(100) NOT NULL,
   SDT CHAR(10) NOT NULL,
   NGAYSINH DATE NOT NULL,
   HESOLUONG INT NOT NULL,
   NGAYVAOLAM DATE NOT NULL,
   PRIMARY KEY (MANV),
   INDEX LA_NGUOI_QUAN_LY_FK (NHA_MANV),
   INDEX ASSOCIATION_14_FK (MAPB)
);


CREATE TABLE PHIEUNHAP (
   MAPHIEUNHAP CHAR(10) NOT NULL,
   MANV CHAR(10) NOT NULL,
   NGAYNHAP DATETIME NOT NULL,
   PRIMARY KEY (MAPHIEUNHAP),
   INDEX KIEM_HANG_FK (MANV)
);

CREATE TABLE LyLich (
    STT INT NOT NULL AUTO_INCREMENT,
    TrinhDoVanHoa VARCHAR(200) NULL,
    DanToc VARCHAR(200) NULL,
    TonGiao VARCHAR(200) NULL,
    TrinhDoChuyenMon VARCHAR(200) NULL,
    NoiThuongTru VARCHAR(200) NULL,
    NoiTamTru VARCHAR(200) NULL,
    NoiSinh VARCHAR(200) NULL,
	MANV CHAR(10) NOT NULL,
    PRIMARY KEY (STT,MANV)
);

CREATE TABLE PHIEUXUAT (
   MAPHIEUXUAT CHAR(10) NOT NULL,
   MACH VARCHAR(10) NOT NULL,
   NGAYXUAT DATETIME NOT NULL,
   THOIGIANNHAPLIEU DATETIME NOT NULL,
   TINHTRANGNHAPLIEU INT NOT NULL,
   PRIMARY KEY (MAPHIEUXUAT),
   INDEX CHI_TIET_DON_HANG_FK (MACH)
);

CREATE TABLE PHONGBAN (
   MAPB CHAR(5) NOT NULL,
   TENPB VARCHAR(100) NOT NULL,
   PRIMARY KEY (MAPB)
);


CREATE TABLE BANGXACTHUC (
	MaXacThuc char(15),
	MANV CHAR(10),
    GhiChuXT TEXT,
    TinhTrangXT bool,
    NgayXT DATE,
    primary key (MaXacThuc)
    
);

ALTER TABLE BANGCAP
   ADD CONSTRAINT FK_BANGCAP_SO_HUU_BA_NHANVIEN FOREIGN KEY (MANV)
      REFERENCES NHANVIEN (MANV);

ALTER TABLE BAOCAO
   ADD CONSTRAINT FK_BAOCAO_GUI_THONG_CUAHANGN FOREIGN KEY (MACH)
      REFERENCES CUAHANGNHUONGQUYEN (MACH);

ALTER TABLE CTPN
   ADD CONSTRAINT FK_CTPN_CTPN_PHIEUNHA FOREIGN KEY (MAPHIEUNHAP)
      REFERENCES PHIEUNHAP (MAPHIEUNHAP);

ALTER TABLE CTPN
   ADD CONSTRAINT FK_CTPN_CTPN2_HANG FOREIGN KEY (MAHANG)
      REFERENCES HANG (MAHANG);

ALTER TABLE CTPX
   ADD CONSTRAINT FK_CTPX_CTPX_PHIEUXUA FOREIGN KEY (MAPHIEUXUAT)
      REFERENCES PHIEUXUAT (MAPHIEUXUAT);

ALTER TABLE CTPX
   ADD CONSTRAINT FK_CTPX_CTPX2_HANG FOREIGN KEY (MAHANG)
      REFERENCES HANG (MAHANG);

ALTER TABLE HANG
   ADD CONSTRAINT FK_HANG_THUOC_KHO_KHO FOREIGN KEY (MAKHO)
      REFERENCES KHO (MAKHO);

ALTER TABLE NGUOITHAN
   ADD CONSTRAINT FK_NGUOITHA_ASSOCIATI_NHANVIEN FOREIGN KEY (MANV)
      REFERENCES NHANVIEN (MANV);

ALTER TABLE NHANVIEN
   ADD CONSTRAINT FK_NHANVIEN_ASSOCIATI_PHONGBAN FOREIGN KEY (MAPB)
      REFERENCES PHONGBAN (MAPB);

ALTER TABLE NHANVIEN
   ADD CONSTRAINT FK_NHANVIEN_LA_NGUOI__NHANVIEN FOREIGN KEY (NHA_MANV)
      REFERENCES NHANVIEN (MANV);

ALTER TABLE PHIEUNHAP
   ADD CONSTRAINT FK_PHIEUNHA_KIEM_HANG_NHANVIEN FOREIGN KEY (MANV)
      REFERENCES NHANVIEN (MANV);

ALTER TABLE CUAHANGNHUONGQUYEN
   ADD CONSTRAINT FK_CUAHANG_BENNNQ FOREIGN KEY (MANHUONGQUYEN)
      REFERENCES BEN_NNQ (MANHUONGQUYEN);

ALTER TABLE CUAHANGNHUONGQUYEN
   ADD CONSTRAINT FK_Cual_tang_NuongQuyen_HOPDONG FOREIGN KEY (MAHD, MANHUONGQUYEN)
      REFERENCES HOPDONG (MAHD, MANHUONGQUYEN);

ALTER TABLE PHIEUXUAT
   ADD CONSTRAINT FK_PHIEUXUAT_CUAHANG FOREIGN KEY (MACH)
      REFERENCES CUAHANGNHUONGQUYEN (MACH);

ALTER TABLE LYLICH
   ADD CONSTRAINT FK_LYLICH_NV FOREIGN KEY (MANV)
      REFERENCES NHANVIEN (MANV);

ALTER TABLE HOPDONG
   ADD CONSTRAINT FK_HOPDONG_GOI FOREIGN KEY (MAGOI)
      REFERENCES GOINHUONGQUYEN (MAGOI);
      
ALTER TABLE NGUOITHAN
   ADD CONSTRAINT FK_NGUOITHAN_NV FOREIGN KEY (MANV)
      REFERENCES NHANVIEN (MANV);
      
alter table BAOCAO
	ADD CONSTRAINT FK_baoCao_xacthuc foreign key(MaXacThuc)
    references BANGXACTHUC(MaXacThuc);
    
alter table BANGXACTHUC
	ADD CONSTRAINT FK_NHANVIEN_XACTHUC FOREIGN KEY(MANV)
		 references NHANVIEN (MANV);
    


      
  

