# Generated by Django 5.2 on 2025-04-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NHANVIEN',
            fields=[
                ('MANV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NHA_MANV', models.CharField(blank=True, max_length=10, null=True)),
                ('HOTEN', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=100)),
                ('SDT', models.CharField(max_length=10)),
                ('NGAYSINH', models.DateField()),
                ('HESOLUONG', models.IntegerField()),
                ('NGAYVAOLAM', models.DateField()),
            ],
            options={
                'db_table': 'NHANVIEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PHONGBAN',
            fields=[
                ('MAPB', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TENPB', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'PHONGBAN',
                'managed': False,
            },
        ),
    ]
