# Generated by Django 5.2 on 2025-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANGCAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SOHIEUBANG', models.CharField(max_length=5)),
                ('SOVAOSO', models.CharField(max_length=20)),
                ('NGAYCAPBANG', models.DateTimeField(null=True)),
                ('XEPLOAI', models.CharField(max_length=100, null=True)),
                ('HINHTHUCDAOTAO', models.CharField(max_length=100, null=True)),
                ('NGUOICAP', models.CharField(max_length=100, null=True)),
                ('CHUYENNGANHDAOTAO', models.CharField(max_length=100, null=True)),
                ('THOIGIANDAOTAO', models.DateTimeField(null=True)),
                ('THOIGIANKETTHUCDAOTAO', models.DateTimeField(null=True)),
                ('NOICAP', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'BANGCAP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BANGXACTHUC',
            fields=[
                ('MaXacThuc', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('GhiChuXT', models.TextField(blank=True, null=True)),
                ('TinhTrangXT', models.BooleanField()),
                ('NgayXT', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BANGXACTHUC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BAOCAO',
            fields=[
                ('MABAOCAO', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('LOAIBAOCAO', models.CharField(max_length=100, null=True)),
                ('NGAYBAOCAO', models.DateTimeField(null=True)),
                ('NOIDUNGBAOCAO', models.TextField(null=True)),
                ('DOANHTHU', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'BAOCAO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BEN_NNQ',
            fields=[
                ('MANHUONGQUYEN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HOTEN', models.CharField(max_length=100)),
                ('SDT', models.CharField(max_length=10)),
                ('EMAIL', models.CharField(max_length=100)),
                ('DIACHI', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'BEN_NNQ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CTPN',
            fields=[
                ('MAPHIEUNHAP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SOLUONGNHAP', models.IntegerField()),
                ('DONGIANHAP', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'CTPN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CUAHANGNHUONGQUYEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MACH', models.CharField(max_length=10, unique=True)),
                ('DIACHI', models.CharField(max_length=200)),
                ('NGAYKHAITRUONG', models.DateTimeField()),
                ('MASOTHUE', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'CUAHANGNHUONGQUYEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GOINHUONGQUYEN',
            fields=[
                ('MAGOI', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TENGOI', models.CharField(max_length=255)),
                ('VONDAUTU', models.DecimalField(decimal_places=4, max_digits=15)),
                ('MOTAGOI', models.TextField()),
            ],
            options={
                'db_table': 'GOINHUONGQUYEN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HANG',
            fields=[
                ('MAHANG', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TENHANG', models.CharField(max_length=255)),
                ('DONVIDOLUONG', models.CharField(max_length=50)),
                ('GIANHAP', models.DecimalField(decimal_places=2, max_digits=15)),
                ('GIABAN', models.DecimalField(decimal_places=2, max_digits=15)),
                ('LOAIHANG', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'HANG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HOPDONG',
            fields=[
                ('MAHD', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CHIPHITONG', models.DecimalField(decimal_places=4, max_digits=15)),
                ('NGAYBATDAU', models.DateField()),
                ('NGAYKETTHUC', models.DateField()),
            ],
            options={
                'db_table': 'HOPDONG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KHO',
            fields=[
                ('MAKHO', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TENKHO', models.CharField(max_length=255)),
                ('DIACHI', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'KHO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LyLich',
            fields=[
                ('STT', models.AutoField(primary_key=True, serialize=False)),
                ('TrinhDoVanHoa', models.CharField(blank=True, max_length=200, null=True)),
                ('DanToc', models.CharField(blank=True, max_length=200, null=True)),
                ('TonGiao', models.CharField(blank=True, max_length=200, null=True)),
                ('TrinhDoChuyenMon', models.CharField(blank=True, max_length=200, null=True)),
                ('NoiThuongTru', models.CharField(blank=True, max_length=200, null=True)),
                ('NoiTamTru', models.CharField(blank=True, max_length=200, null=True)),
                ('NoiSinh', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'LyLich',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NGUOITHAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TENNT', models.CharField(max_length=100)),
                ('QUANHE', models.CharField(max_length=200)),
                ('SDTNT', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'NGUOITHAN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PHIEUNHAP',
            fields=[
                ('MAPHIEUNHAP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NGAYNHAP', models.DateTimeField()),
            ],
            options={
                'db_table': 'PHIEUNHAP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PHIEUXUAT',
            fields=[
                ('MAPHIEUXUAT', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NGAYXUAT', models.DateTimeField()),
                ('THOIGIANNHAPLIEU', models.DateTimeField()),
                ('TINHTRANGNHAPLIEU', models.IntegerField()),
            ],
            options={
                'db_table': 'PHIEUXUAT',
                'managed': False,
            },
        ),
    ]
