# Generated by Django 5.2 on 2025-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_bangcap_bangxacthuc_baocao_ben_nnq_ctpn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTPX',
            fields=[
                ('MAPHIEUXUAT', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SOLUONGXUAT', models.IntegerField()),
                ('DONGIAXUAT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DONVITINH', models.CharField(max_length=100)),
                ('GIAMGIABAN', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CTPX',
                'managed': False,
            },
        ),
    ]
